../bin/grader.py -d 01_howdy
#../bin/grader.py -d 02_divide
#../bin/grader.py -d 03_dna
#../bin/grader.py -d 04_revc
#../bin/grader.py -d 05_gc
#../bin/grader.py -d 06_rna
#../bin/grader.py -d 07_syndna
#../bin/grader.py -d 08_common
#../bin/grader.py -d 09_blastomatic
#../bin/grader.py -d 10_conserved
#../bin/grader.py -d 11_run_length
#../bin/grader.py -d 12_seqmagique
