cd ~/workspace/assignments/01_howdy ; make test
#cd ~/workspace/assignments/02_divide ; make test
#cd ~/workspace/assignments/03_dna ; make test
#cd ~/workspace/assignments/04_revc ; make test
#cd ~/workspace/assignments/05_gc ; make test
#cd ~/workspace/assignments/06_rna ; make test
#cd ~/workspace/assignments/07_syndna ; make test
#cd ~/workspace/assignments/08_common ; make test
#cd ~/workspace/assignments/09_blastomatic ; make test
#cd ~/workspace/assignments/10_conserved ; make test
#cd ~/workspace/assignments/11_run_length ; make test
#cd ~/workspace/assignments/12_seqmagique ; make test
