../bin/grader.py -d 01_hello
../bin/grader.py -d 02_crowsnest
../bin/grader.py -d 03_picnic
../bin/grader.py -d 04_jump_the_five
../bin/grader.py -d 05_howler
../bin/grader.py -d 06_wc
../bin/grader.py -d 07_gashlycrumb
../bin/grader.py -d 08_apples_and_bananas
../bin/grader.py -d 09_abuse
../bin/grader.py -d 10_telephone
../bin/grader.py -d 11_bottles_of_beer
../bin/grader.py -d 12_ransom
../bin/grader.py -d 13_twelve_days
../bin/grader.py -d 14_rhymer
../bin/grader.py -d 15_kentucky_friar
../bin/grader.py -d 16_scrambler
../bin/grader.py -d 17_mad_libs
../bin/grader.py -d 18_gematria
../bin/grader.py -d 19_wod
../bin/grader.py -d 20_password
../bin/grader.py -d 21_tictactoe
../bin/grader.py -d 22_itictactoe
