cd ~/workspace/extra_practice/01_salutations ; make test
#cd ~/workspace/extra_practice/02_sum ; make test
#cd ~/workspace/extra_practice/03_solfege ; make test
#cd ~/workspace/extra_practice/04_cat ; make test
#cd ~/workspace/extra_practice/05_proteins ; make test
#cd ~/workspace/extra_practice/06_iupac ; make test
#cd ~/workspace/extra_practice/07_fastx_sampler ; make test
#cd ~/workspace/extra_practice/08_kmers ; make test
#cd ~/workspace/extra_practice/09_csvfilter ; make test
#cd ~/workspace/extra_practice/10_hamm ; make test
#cd ~/workspace/extra_practice/11_fasta ; make test
#cd ~/workspace/extra_practice/12_grep ; make test
