../bin/grader.py -d 01_salutations
../bin/grader.py -d 02_sum
../bin/grader.py -d 03_solfege
../bin/grader.py -d 04_cat
../bin/grader.py -d 05_proteins
../bin/grader.py -d 06_iupac
../bin/grader.py -d 07_fastx_sampler
../bin/grader.py -d 08_kmers
../bin/grader.py -d 09_csvfilter
../bin/grader.py -d 10_hamm
../bin/grader.py -d 11_fasta
../bin/grader.py -d 12_grep
